import type { CallList, UserSettings, GoalConfig } from "./types";

// デモ用目標設定（3人チーム・1人10件/日・月10アポが目標）
export const DEMO_GOALS: GoalConfig = {
  dailyCallsPerPerson: 10,
  monthlyAppoPerPerson: 3,
  teamDailyCalls: 30,
  teamMonthlyAppo: 10,
};

export const DEMO_USER: UserSettings = {
  name: "山崎 徳",
  calendarUrl: "",
  reportFormUrl: "",
  phone: "070-4425-0729",
  email: "toku.yamazaki@randd-inc.com",
};

// ── List 1: IT・SaaS企業 ──────────────────────────────────────────
const LIST1: CallList = {
  id: "demo-list-1",
  name: "IT・SaaS企業リスト",
  industry: "情報通信",
  fiscalMonthFrom: "3",
  fiscalMonthTo: "9",
  revenueFrom: "5億",
  revenueTo: "50億",
  createdAt: "2026-04-10T09:00:00.000Z",
  companies: [
    {
      id: "demo-c-001",
      company: "株式会社クラウドテック",
      phone: "03-4521-0001",
      industry: "情報通信",
      subIndustry: "SaaS・クラウド",
      employees: "120",
      revenue: "12億",
      address: "東京都渋谷区道玄坂1-2-3",
      contactName: "鈴木 賢司",
      directPhone: "03-4521-0011",
      contactEmail: "k.suzuki@cloudtech.example.com",
      assignee: "山田 太郎",
      latestResult: "アポ獲得",
      nextDate: "2026-04-18",
      callHistory: [
        {
          id: "h-001-2",
          date: "2026-04-16",
          result: "アポ獲得",
          memo: "採用課題が深刻。4/18 15時でアポ確定。人事部長同席",
          assignee: "山田 太郎",
          products: ["採用支援"],
          challenges: ["採用に困っている"],
          interests: ["導入事例・実績", "費用対効果"],
        },
        {
          id: "h-001-1",
          date: "2026-04-15",
          result: "担当者不在",
          memo: "人事担当は午後のみ在席とのこと",
          assignee: "山田 太郎",
          products: [],
          challenges: [],
          interests: [],
        },
      ],
      importedAt: "2026-04-10T09:00:00.000Z",
    },
    {
      id: "demo-c-002",
      company: "株式会社デジタルフォース",
      phone: "03-4521-0002",
      industry: "情報通信",
      subIndustry: "ITコンサルティング",
      employees: "85",
      revenue: "8億",
      address: "東京都新宿区西新宿3-4-5",
      contactName: "中村 美咲",
      directPhone: "",
      contactEmail: "m.nakamura@digitalforce.example.com",
      assignee: "山田 太郎",
      latestResult: "資料送付",
      nextDate: "2026-04-22",
      callHistory: [
        {
          id: "h-002-2",
          date: "2026-04-16",
          result: "資料送付",
          memo: "DX推進担当の中村さん。具体的な数字を求めている",
          assignee: "山田 太郎",
          products: ["DX支援"],
          challenges: ["DXを進めたい"],
          interests: ["具体的な数字", "サービスの独自性"],
        },
        {
          id: "h-002-1",
          date: "2026-04-14",
          result: "再コール",
          memo: "担当者会議中。来週改めて",
          assignee: "山田 太郎",
          products: [],
          challenges: [],
          interests: [],
        },
      ],
      importedAt: "2026-04-10T09:00:00.000Z",
    },
    {
      id: "demo-c-003",
      company: "合同会社ネクストベース",
      phone: "03-4521-0003",
      industry: "情報通信",
      subIndustry: "Webサービス",
      employees: "45",
      revenue: "3億",
      address: "東京都港区六本木7-8-9",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "佐藤 花子",
      latestResult: "再コール",
      nextDate: "2026-04-20",
      callHistory: [
        {
          id: "h-003-2",
          date: "2026-04-16",
          result: "再コール",
          memo: "田中部長は来週月曜午前に在席。再コール予定",
          assignee: "佐藤 花子",
          products: ["採用支援"],
          challenges: ["採用に困っている"],
          interests: ["費用対効果"],
        },
        {
          id: "h-003-1",
          date: "2026-04-13",
          result: "担当者不在",
          memo: "",
          assignee: "佐藤 花子",
          products: [],
          challenges: [],
          interests: [],
        },
      ],
      importedAt: "2026-04-10T09:00:00.000Z",
    },
    {
      id: "demo-c-004",
      company: "株式会社スマートリンク",
      phone: "03-4521-0004",
      industry: "情報通信",
      subIndustry: "システム開発",
      employees: "200",
      revenue: "22億",
      address: "神奈川県横浜市西区みなとみらい2-3-4",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "佐藤 花子",
      latestResult: "担当者不在",
      nextDate: "2026-04-17",
      callHistory: [
        {
          id: "h-004-2",
          date: "2026-04-16",
          result: "担当者不在",
          memo: "人事部長は出張中。17日以降に再コール",
          assignee: "佐藤 花子",
          products: [],
          challenges: [],
          interests: [],
        },
        {
          id: "h-004-1",
          date: "2026-04-11",
          result: "担当NG",
          memo: "",
          assignee: "佐藤 花子",
          products: [],
          challenges: [],
          interests: [],
          ngReason: "競合他社と契約中",
        },
      ],
      importedAt: "2026-04-10T09:00:00.000Z",
    },
    {
      id: "demo-c-005",
      company: "株式会社テックピア",
      phone: "03-4521-0005",
      industry: "情報通信",
      subIndustry: "SaaS・クラウド",
      employees: "310",
      revenue: "35億",
      address: "東京都千代田区大手町1-2-3",
      contactName: "松本 大輝",
      directPhone: "03-4521-0055",
      contactEmail: "d.matsumoto@techpia.example.com",
      assignee: "田中 健",
      latestResult: "アポ獲得",
      nextDate: "2026-04-21",
      callHistory: [
        {
          id: "h-005-2",
          date: "2026-04-16",
          result: "アポ獲得",
          memo: "採用コストを下げたいとのこと。4/21 14時でアポ",
          assignee: "田中 健",
          products: ["採用支援", "WEBマーケティング"],
          challenges: ["採用に困っている", "コスト削減したい"],
          interests: ["費用対効果", "導入事例・実績"],
        },
        {
          id: "h-005-1",
          date: "2026-04-10",
          result: "受付NG",
          memo: "",
          assignee: "田中 健",
          products: [],
          challenges: [],
          interests: [],
          ngReason: "電話お断り",
        },
      ],
      importedAt: "2026-04-10T09:00:00.000Z",
    },
    {
      id: "demo-c-006",
      company: "株式会社アイリスデータ",
      phone: "03-4521-0006",
      industry: "情報通信",
      subIndustry: "データ分析",
      employees: "78",
      revenue: "7億",
      address: "東京都目黒区目黒1-5-6",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "田中 健",
      latestResult: "担当者不在",
      nextDate: "2026-04-18",
      callHistory: [
        {
          id: "h-006-2",
          date: "2026-04-16",
          result: "担当者不在",
          memo: "受付に担当者名を確認。人事の西田さんに次回指名",
          assignee: "田中 健",
          products: [],
          challenges: [],
          interests: [],
        },
        {
          id: "h-006-1",
          date: "2026-04-12",
          result: "担当者不在",
          memo: "",
          assignee: "田中 健",
          products: [],
          challenges: [],
          interests: [],
        },
      ],
      importedAt: "2026-04-10T09:00:00.000Z",
    },
    {
      id: "demo-c-007",
      company: "有限会社オープンシード",
      phone: "03-4521-0007",
      industry: "情報通信",
      subIndustry: "Webマーケティング",
      employees: "32",
      revenue: "2億",
      address: "大阪府大阪市北区梅田2-4-6",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "山田 太郎",
      latestResult: "受付NG",
      nextDate: "",
      callHistory: [
        {
          id: "h-007-2",
          date: "2026-04-16",
          result: "受付NG",
          memo: "",
          assignee: "山田 太郎",
          products: [],
          challenges: [],
          interests: [],
          ngReason: "窓口NG",
        },
        {
          id: "h-007-1",
          date: "2026-04-12",
          result: "受付NG",
          memo: "",
          assignee: "山田 太郎",
          products: [],
          challenges: [],
          interests: [],
          ngReason: "電話お断り",
        },
      ],
      importedAt: "2026-04-10T09:00:00.000Z",
    },
    {
      id: "demo-c-008",
      company: "株式会社ブライトウェーブ",
      phone: "052-234-0008",
      industry: "情報通信",
      subIndustry: "ITコンサルティング",
      employees: "155",
      revenue: "18億",
      address: "愛知県名古屋市中区栄3-7-8",
      contactName: "伊藤 さやか",
      directPhone: "",
      contactEmail: "",
      assignee: "佐藤 花子",
      latestResult: "資料送付",
      nextDate: "2026-04-23",
      callHistory: [
        {
          id: "h-008-2",
          date: "2026-04-16",
          result: "資料送付",
          memo: "業務効率化に興味あり。SNS運用支援も検討したい",
          assignee: "佐藤 花子",
          products: ["業務効率化ツール", "SNS運用支援"],
          challenges: ["業務を効率化したい"],
          interests: ["スピード感", "費用対効果"],
        },
        {
          id: "h-008-1",
          date: "2026-04-13",
          result: "再コール",
          memo: "",
          assignee: "佐藤 花子",
          products: [],
          challenges: [],
          interests: [],
        },
      ],
      importedAt: "2026-04-10T09:00:00.000Z",
    },
    {
      id: "demo-c-009",
      company: "株式会社フューチャーコード",
      phone: "03-5678-0009",
      industry: "情報通信",
      subIndustry: "システム開発",
      employees: "62",
      revenue: "5億",
      address: "東京都品川区大崎1-2-3",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "田中 健",
      latestResult: "再コール",
      nextDate: "2026-04-21",
      callHistory: [
        {
          id: "h-009-2",
          date: "2026-04-16",
          result: "再コール",
          memo: "採用担当は週1回しか出社しない。火曜に再コール",
          assignee: "田中 健",
          products: [],
          challenges: [],
          interests: [],
        },
        {
          id: "h-009-1",
          date: "2026-04-11",
          result: "担当者不在",
          memo: "",
          assignee: "田中 健",
          products: [],
          challenges: [],
          interests: [],
        },
      ],
      importedAt: "2026-04-10T09:00:00.000Z",
    },
    {
      id: "demo-c-010",
      company: "株式会社ライズテクノロジ",
      phone: "03-6789-0010",
      industry: "情報通信",
      subIndustry: "SaaS・クラウド",
      employees: "190",
      revenue: "20億",
      address: "東京都港区赤坂4-5-6",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "山田 太郎",
      latestResult: "担当者不在",
      nextDate: "2026-04-17",
      callHistory: [
        {
          id: "h-010-1",
          date: "2026-04-16",
          result: "担当者不在",
          memo: "来週月曜の午前中に再コール",
          assignee: "山田 太郎",
          products: [],
          challenges: [],
          interests: [],
        },
      ],
      importedAt: "2026-04-10T09:00:00.000Z",
    },
  ],
};

// ── List 2: 製造・メーカーリスト ──────────────────────────────────
const LIST2: CallList = {
  id: "demo-list-2",
  name: "製造・メーカーリスト",
  industry: "製造業",
  fiscalMonthFrom: "3",
  fiscalMonthTo: "12",
  revenueFrom: "10億",
  revenueTo: "100億",
  createdAt: "2026-04-12T09:00:00.000Z",
  companies: [
    {
      id: "demo-c-101",
      company: "株式会社ミライ精工",
      phone: "044-321-1001",
      industry: "製造業",
      subIndustry: "精密機器製造",
      employees: "420",
      revenue: "48億",
      address: "神奈川県川崎市幸区大宮町3-4",
      contactName: "高橋 誠一",
      directPhone: "044-321-1011",
      contactEmail: "",
      assignee: "佐藤 花子",
      latestResult: "アポ獲得",
      nextDate: "2026-04-17",
      callHistory: [
        {
          id: "h-101-2",
          date: "2026-04-16",
          result: "アポ獲得",
          memo: "新卒採用の課題が深刻。4/17 10時でアポ。人事部長同席",
          assignee: "佐藤 花子",
          products: ["採用支援"],
          challenges: ["採用に困っている", "リード獲得したい"],
          interests: ["導入事例・実績", "費用対効果"],
        },
        {
          id: "h-101-1",
          date: "2026-04-15",
          result: "担当者不在",
          memo: "高橋部長は終日外出",
          assignee: "佐藤 花子",
          products: [],
          challenges: [],
          interests: [],
        },
      ],
      importedAt: "2026-04-12T09:00:00.000Z",
    },
    {
      id: "demo-c-102",
      company: "有限会社サンライズ工業",
      phone: "06-4321-1002",
      industry: "製造業",
      subIndustry: "金属加工",
      employees: "95",
      revenue: "11億",
      address: "大阪府東大阪市高井田本通1-2-3",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "山田 太郎",
      latestResult: "担当者不在",
      nextDate: "2026-04-17",
      callHistory: [
        {
          id: "h-102-2",
          date: "2026-04-16",
          result: "担当者不在",
          memo: "人事の木村さんは午後のみ在席",
          assignee: "山田 太郎",
          products: [],
          challenges: [],
          interests: [],
        },
        {
          id: "h-102-1",
          date: "2026-04-14",
          result: "担当者不在",
          memo: "",
          assignee: "山田 太郎",
          products: [],
          challenges: [],
          interests: [],
        },
      ],
      importedAt: "2026-04-12T09:00:00.000Z",
    },
    {
      id: "demo-c-103",
      company: "株式会社ホライゾン化学",
      phone: "03-4321-1003",
      industry: "製造業",
      subIndustry: "化学・素材",
      employees: "680",
      revenue: "92億",
      address: "東京都江東区有明3-7-18",
      contactName: "渡辺 敦子",
      directPhone: "03-4321-1033",
      contactEmail: "a.watanabe@horizon-chem.example.com",
      assignee: "佐藤 花子",
      latestResult: "担当NG",
      nextDate: "",
      callHistory: [
        {
          id: "h-103-2",
          date: "2026-04-16",
          result: "担当NG",
          memo: "今期は採用計画なし。来期改めて",
          assignee: "佐藤 花子",
          products: [],
          challenges: [],
          interests: [],
          ngReason: "タイミングNG",
        },
        {
          id: "h-103-1",
          date: "2026-04-13",
          result: "資料送付",
          memo: "理系採用に特化したコンテンツを希望",
          assignee: "佐藤 花子",
          products: ["採用支援"],
          challenges: ["採用に困っている"],
          interests: ["サービスの独自性"],
        },
      ],
      importedAt: "2026-04-12T09:00:00.000Z",
    },
    {
      id: "demo-c-104",
      company: "株式会社ノースランド食品",
      phone: "011-234-1004",
      industry: "製造業",
      subIndustry: "食品・飲料",
      employees: "230",
      revenue: "26億",
      address: "北海道札幌市中央区北一条西4丁目",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "田中 健",
      latestResult: "担当NG",
      nextDate: "",
      callHistory: [
        {
          id: "h-104-2",
          date: "2026-04-16",
          result: "担当NG",
          memo: "",
          assignee: "田中 健",
          products: [],
          challenges: [],
          interests: [],
          ngReason: "予算なし",
        },
        {
          id: "h-104-1",
          date: "2026-04-12",
          result: "担当者不在",
          memo: "",
          assignee: "田中 健",
          products: [],
          challenges: [],
          interests: [],
        },
      ],
      importedAt: "2026-04-12T09:00:00.000Z",
    },
    {
      id: "demo-c-105",
      company: "合同会社セントラル部品",
      phone: "052-345-1005",
      industry: "製造業",
      subIndustry: "自動車部品",
      employees: "540",
      revenue: "63億",
      address: "愛知県豊田市トヨタ町1-2",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "山田 太郎",
      latestResult: "再コール",
      nextDate: "2026-04-21",
      callHistory: [
        {
          id: "h-105-1",
          date: "2026-04-15",
          result: "再コール",
          memo: "採用担当は来週戻り。4/21以降に再コール",
          assignee: "山田 太郎",
          products: [],
          challenges: [],
          interests: [],
        },
      ],
      importedAt: "2026-04-12T09:00:00.000Z",
    },
    {
      id: "demo-c-106",
      company: "株式会社グリーンエナジー製作",
      phone: "048-234-1006",
      industry: "製造業",
      subIndustry: "環境・エネルギー機器",
      employees: "175",
      revenue: "19億",
      address: "埼玉県さいたま市大宮区桜木町2-3-4",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "田中 健",
      latestResult: "受付NG",
      nextDate: "",
      callHistory: [
        {
          id: "h-106-1",
          date: "2026-04-16",
          result: "受付NG",
          memo: "",
          assignee: "田中 健",
          products: [],
          challenges: [],
          interests: [],
          ngReason: "電話お断り",
        },
      ],
      importedAt: "2026-04-12T09:00:00.000Z",
    },
    {
      id: "demo-c-107",
      company: "株式会社東洋マシナリー",
      phone: "044-567-1007",
      industry: "製造業",
      subIndustry: "産業機械",
      employees: "350",
      revenue: "41億",
      address: "神奈川県横浜市港北区新横浜3-4-5",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "佐藤 花子",
      latestResult: "担当者不在",
      nextDate: "2026-04-18",
      callHistory: [
        {
          id: "h-107-2",
          date: "2026-04-16",
          result: "担当者不在",
          memo: "人事部全員が研修中。18日以降に連絡",
          assignee: "佐藤 花子",
          products: [],
          challenges: [],
          interests: [],
        },
        {
          id: "h-107-1",
          date: "2026-04-11",
          result: "受付NG",
          memo: "",
          assignee: "佐藤 花子",
          products: [],
          challenges: [],
          interests: [],
          ngReason: "担当者不在が続く",
        },
      ],
      importedAt: "2026-04-12T09:00:00.000Z",
    },
    {
      id: "demo-c-108",
      company: "株式会社ビジョン金属",
      phone: "06-7890-1008",
      industry: "製造業",
      subIndustry: "非鉄金属",
      employees: "280",
      revenue: "33億",
      address: "大阪府大阪市西淀川区御幣島5-6-7",
      contactName: "木下 直樹",
      directPhone: "",
      contactEmail: "",
      assignee: "山田 太郎",
      latestResult: "資料送付",
      nextDate: "2026-04-24",
      callHistory: [
        {
          id: "h-108-2",
          date: "2026-04-16",
          result: "資料送付",
          memo: "DX化を進めたいとのこと。業務効率化ツールに関心",
          assignee: "山田 太郎",
          products: ["業務効率化ツール", "DX支援"],
          challenges: ["業務を効率化したい", "DXを進めたい"],
          interests: ["費用対効果", "サポート体制"],
        },
        {
          id: "h-108-1",
          date: "2026-04-15",
          result: "担当NG",
          memo: "",
          assignee: "山田 太郎",
          products: [],
          challenges: [],
          interests: [],
          ngReason: "興味なし",
        },
      ],
      importedAt: "2026-04-12T09:00:00.000Z",
    },
    {
      id: "demo-c-109",
      company: "有限会社ファーストプリント",
      phone: "03-2345-1009",
      industry: "製造業",
      subIndustry: "印刷・出版",
      employees: "68",
      revenue: "6億",
      address: "東京都墨田区錦糸町2-3-4",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "田中 健",
      latestResult: "担当者不在",
      nextDate: "2026-04-17",
      callHistory: [
        {
          id: "h-109-1",
          date: "2026-04-16",
          result: "担当者不在",
          memo: "受付で担当者名を確認。採用担当は増田さん",
          assignee: "田中 健",
          products: [],
          challenges: [],
          interests: [],
        },
      ],
      importedAt: "2026-04-12T09:00:00.000Z",
    },
    {
      id: "demo-c-110",
      company: "株式会社ソーラーテクノ",
      phone: "03-3456-1010",
      industry: "製造業",
      subIndustry: "環境・エネルギー機器",
      employees: "142",
      revenue: "16億",
      address: "東京都江東区東雲1-2-3",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "佐藤 花子",
      latestResult: "受付NG",
      nextDate: "",
      callHistory: [
        {
          id: "h-110-2",
          date: "2026-04-16",
          result: "受付NG",
          memo: "",
          assignee: "佐藤 花子",
          products: [],
          challenges: [],
          interests: [],
          ngReason: "リスト掲載NG",
        },
        {
          id: "h-110-1",
          date: "2026-04-10",
          result: "担当NG",
          memo: "",
          assignee: "佐藤 花子",
          products: [],
          challenges: [],
          interests: [],
          ngReason: "予算なし",
        },
      ],
      importedAt: "2026-04-12T09:00:00.000Z",
    },
  ],
};

// ── List 3: 不動産・建設リスト ──────────────────────────────────────
const LIST3: CallList = {
  id: "demo-list-3",
  name: "不動産・建設リスト",
  industry: "不動産・建設",
  fiscalMonthFrom: "3",
  fiscalMonthTo: "9",
  revenueFrom: "20億",
  revenueTo: "200億",
  createdAt: "2026-04-14T09:00:00.000Z",
  companies: [
    {
      id: "demo-c-201",
      company: "株式会社アーバン不動産",
      phone: "03-5678-2001",
      industry: "不動産",
      subIndustry: "賃貸・売買仲介",
      employees: "340",
      revenue: "58億",
      address: "東京都港区南青山3-4-5",
      contactName: "小林 翔太",
      directPhone: "03-5678-2011",
      contactEmail: "s.kobayashi@urban-re.example.com",
      assignee: "田中 健",
      latestResult: "アポ獲得",
      nextDate: "2026-04-22",
      callHistory: [
        {
          id: "h-201-1",
          date: "2026-04-16",
          result: "アポ獲得",
          memo: "エージェント採用の課題あり。4/22 13時でアポ確定",
          assignee: "田中 健",
          products: ["採用支援", "WEBマーケティング"],
          challenges: ["採用に困っている", "新規顧客を増やしたい"],
          interests: ["費用対効果", "スピード感"],
        },
      ],
      importedAt: "2026-04-14T09:00:00.000Z",
    },
    {
      id: "demo-c-202",
      company: "株式会社ライフホーム建設",
      phone: "044-678-2002",
      industry: "建設",
      subIndustry: "住宅建設",
      employees: "510",
      revenue: "72億",
      address: "神奈川県横浜市都筑区中川1-2-3",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "山田 太郎",
      latestResult: "資料送付",
      nextDate: "2026-04-25",
      callHistory: [
        {
          id: "h-202-2",
          date: "2026-04-16",
          result: "資料送付",
          memo: "採用広告費の削減を検討中。事例資料を送付",
          assignee: "山田 太郎",
          products: ["採用支援"],
          challenges: ["採用に困っている", "コスト削減したい"],
          interests: ["費用対効果", "他社との違い"],
        },
        {
          id: "h-202-1",
          date: "2026-04-14",
          result: "担当者不在",
          memo: "",
          assignee: "山田 太郎",
          products: [],
          challenges: [],
          interests: [],
        },
      ],
      importedAt: "2026-04-14T09:00:00.000Z",
    },
    {
      id: "demo-c-203",
      company: "株式会社グランドプロパティ",
      phone: "03-6789-2003",
      industry: "不動産",
      subIndustry: "不動産開発",
      employees: "280",
      revenue: "95億",
      address: "東京都千代田区丸の内1-2-3",
      contactName: "佐々木 和也",
      directPhone: "03-6789-2033",
      contactEmail: "",
      assignee: "佐藤 花子",
      latestResult: "再コール",
      nextDate: "2026-04-21",
      callHistory: [
        {
          id: "h-203-2",
          date: "2026-04-16",
          result: "再コール",
          memo: "採用部長が来週月曜に戻る。21日に再コール",
          assignee: "佐藤 花子",
          products: ["採用支援"],
          challenges: ["採用に困っている"],
          interests: ["導入事例・実績"],
        },
        {
          id: "h-203-1",
          date: "2026-04-15",
          result: "アポ獲得",
          memo: "4/18でアポ取れたが担当者都合でキャンセル",
          assignee: "佐藤 花子",
          products: ["採用支援"],
          challenges: ["採用に困っている"],
          interests: ["費用対効果"],
        },
      ],
      importedAt: "2026-04-14T09:00:00.000Z",
    },
    {
      id: "demo-c-204",
      company: "株式会社シティ開発",
      phone: "06-4567-2004",
      industry: "不動産",
      subIndustry: "商業施設開発",
      employees: "190",
      revenue: "44億",
      address: "大阪府大阪市中央区本町4-5-6",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "田中 健",
      latestResult: "再コール",
      nextDate: "2026-04-21",
      callHistory: [
        {
          id: "h-204-1",
          date: "2026-04-16",
          result: "再コール",
          memo: "担当者は週3出社。月水金に再コール",
          assignee: "田中 健",
          products: [],
          challenges: [],
          interests: [],
        },
      ],
      importedAt: "2026-04-14T09:00:00.000Z",
    },
    {
      id: "demo-c-205",
      company: "株式会社ネオハウジング",
      phone: "03-2345-2005",
      industry: "建設",
      subIndustry: "マンション建設",
      employees: "430",
      revenue: "67億",
      address: "東京都江東区豊洲5-6-7",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "山田 太郎",
      latestResult: "担当者不在",
      nextDate: "2026-04-18",
      callHistory: [
        {
          id: "h-205-1",
          date: "2026-04-16",
          result: "担当者不在",
          memo: "採用担当は午後2時以降に在席",
          assignee: "山田 太郎",
          products: [],
          challenges: [],
          interests: [],
        },
      ],
      importedAt: "2026-04-14T09:00:00.000Z",
    },
    {
      id: "demo-c-206",
      company: "株式会社サクラ建設",
      phone: "048-345-2006",
      industry: "建設",
      subIndustry: "土木・インフラ",
      employees: "620",
      revenue: "88億",
      address: "埼玉県さいたま市浦和区高砂3-4-5",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "佐藤 花子",
      latestResult: "担当NG",
      nextDate: "",
      callHistory: [
        {
          id: "h-206-1",
          date: "2026-04-16",
          result: "担当NG",
          memo: "",
          assignee: "佐藤 花子",
          products: [],
          challenges: [],
          interests: [],
          ngReason: "担当者変更",
        },
      ],
      importedAt: "2026-04-14T09:00:00.000Z",
    },
    {
      id: "demo-c-207",
      company: "株式会社フロンティア工務",
      phone: "052-456-2007",
      industry: "建設",
      subIndustry: "リノベーション",
      employees: "88",
      revenue: "12億",
      address: "愛知県名古屋市熱田区金山1-2-3",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "田中 健",
      latestResult: "受付NG",
      nextDate: "",
      callHistory: [
        {
          id: "h-207-1",
          date: "2026-04-16",
          result: "受付NG",
          memo: "",
          assignee: "田中 健",
          products: [],
          challenges: [],
          interests: [],
          ngReason: "番号違い",
        },
      ],
      importedAt: "2026-04-14T09:00:00.000Z",
    },
    {
      id: "demo-c-208",
      company: "株式会社メイプルリアルティ",
      phone: "03-5432-2008",
      industry: "不動産",
      subIndustry: "賃貸管理",
      employees: "145",
      revenue: "22億",
      address: "東京都新宿区新宿5-6-7",
      contactName: "田村 智子",
      directPhone: "",
      contactEmail: "t.tamura@maple-re.example.com",
      assignee: "山田 太郎",
      latestResult: "再コール",
      nextDate: "2026-04-18",
      callHistory: [
        {
          id: "h-208-1",
          date: "2026-04-15",
          result: "再コール",
          memo: "採用に課題を感じているとのこと。来週改めてご提案",
          assignee: "山田 太郎",
          products: ["採用支援"],
          challenges: ["採用に困っている"],
          interests: ["費用対効果"],
        },
      ],
      importedAt: "2026-04-14T09:00:00.000Z",
    },
    {
      id: "demo-c-209",
      company: "株式会社プレミア住宅",
      phone: "06-5678-2009",
      industry: "建設",
      subIndustry: "注文住宅",
      employees: "220",
      revenue: "35億",
      address: "大阪府吹田市江坂町1-2-3",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "田中 健",
      latestResult: "資料送付",
      nextDate: "2026-04-24",
      callHistory: [
        {
          id: "h-209-1",
          date: "2026-04-16",
          result: "資料送付",
          memo: "SNS採用に興味あり。事例資料をメールで送付",
          assignee: "田中 健",
          products: ["採用支援", "SNS運用支援"],
          challenges: ["採用に困っている", "ブランド認知を上げたい"],
          interests: ["他社との違い", "導入事例・実績"],
        },
      ],
      importedAt: "2026-04-14T09:00:00.000Z",
    },
    {
      id: "demo-c-210",
      company: "株式会社ハーモニー地所",
      phone: "03-6543-2010",
      industry: "不動産",
      subIndustry: "不動産開発",
      employees: "380",
      revenue: "82億",
      address: "東京都渋谷区恵比寿2-3-4",
      contactName: "",
      directPhone: "",
      contactEmail: "",
      assignee: "",
      latestResult: null,
      nextDate: "",
      callHistory: [],
      importedAt: "2026-04-14T09:00:00.000Z",
    },
  ],
};

export const DEMO_LISTS: CallList[] = [LIST1, LIST2, LIST3];
